modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPLv3"

[[mods]]
modId = "itemscroller"
version = "${version}"
displayName = "Rock'n Roller"
displayURL="https://github.com/ThinkingStudios/ItemScroller-Forge" #optional
logoFile="icon.png" #optional
credits="masa" #optional
authors="TexTrue, ThinkingStudio" #optional
description = '''
Move items in inventory GUIs by scrolling the mouse wheel or dragging over slots
'''

[[dependencies.itemscroller]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemscroller]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.itemscroller]]
modId = "malilib"
mandatory = true
versionRange = "[0.1.5,)"
ordering = "NONE"
side = "BOTH"
