modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPLv3"

[[mods]]
modId = "rocknroller"
version = "${version}"
displayName = "Rock'n Roller"
displayURL="https://github.com/ThinkingStudios/ItemScroller-Forge" #optional
logoFile="icon.png" #optional
credits="masa" #optional
authors="TexTrue, ThinkingStudio" #optional
description = '''
ItemScroller unofficial (Neo)Forge port.

Move items in inventory GUIs by scrolling the mouse wheel or dragging over slots
'''

[[mixins]]
config = "mixins.itemscroller.json"

[[dependencies.rocknroller]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rocknroller]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rocknroller]]
modId = "mafglib"
type = "required"
versionRange = "[0.2.0,)"
ordering = "NONE"
side = "BOTH"
